[variables]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "gcc", "pip"]

[phases.install]
cmds = [
  "cd Backend && pip install -r requirements.txt",
  "cd Frontend && npm ci"
]

[phases.build]
cmds = [
  "cd Frontend && npm run build"
]

[start]
cmd = "cd Backend && uvicorn main:app --host 0.0.0.0 --port $PORT"