[[services]]
name = "backend"
source = "Backend"

[services.build]
builder = "NIXPACKS"

[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "frontend" 
source = "Frontend"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[services.deploy]
startCommand = "npx serve -s build -l $PORT"