services:
  - type: web
    name: fitness-tracker-backend
    runtime: python
    buildCommand: "cd Backend && pip install -r requirements.txt"
    startCommand: "cd Backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./data.db
      - key: JWT_SECRET
        generateValue: true
    
  - type: web  
    name: fitness-tracker-frontend
    runtime: node
    buildCommand: "cd Frontend && npm install && npm run build"
    startCommand: "cd Frontend && npx serve -s build -l $PORT"
    staticPublishPath: Frontend/build